server:
  port: 8094
  
spring:
  data:
    mongodb:
        uri: mongodb+srv://bootcam-proyecto-01:z2MmbUXIH0ZOSUlm@cluster0.lds0o.mongodb.net/DB-ACCOUNT-WITHDRAWAL?retryWrites=true&w=majority
  cloud:
    discovery:
        enabled: true
    gateway:
        discovery:
            locator:
                enabled: true
                lower-case-service-id: true      
        
eureka:
  instance:
     hostname: localhost
     #hostname: eureka-service-contenedor
     prefer-ip-address: true
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
        defaultZone: http://${eureka.instance.hostname}:8761/eureka/ 