server:
  port: 8089
kafka:
  topic:
    name-order: transaction-request-order
    name-confirmation: transaction-request-confirmation
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer