server:
  port: 8098

spring:
  cloud:
    discovery:
        enabled: true
    gateway:
        discovery:
            locator:
                enabled: true
                lower-case-service-id: true  
                
eureka:
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
        default-zone: http://localhost:8761/eureka